# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'The Coding Couch'
description:         'The Coding Couch is a collection of musings and coverage on everything new in code, gadgets, and life.'
tagline:             'Sit and Relax a Bit...'
url:                 'http://thecodingcouch.com'
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Taylor Dolezal
  url:               https://twitter.com/onlydole
